### ISSUE TITLE
the set() function generated elements order

### ISSUE THREAD

**Issue by alexwenbj** [skulpt/skulpt#1028]
In python,the set() generate elements in different order for every execution.But in skulpt, it generate the fix order for every execution.For example, in Skulpt:
`print(set('google'))`
always get the result:
`{'e', 'o', 'g', 'l'}`
but in Python,the output result is different for every execution:
`{'e', 'l', 'o', 'g'}`
`{'l', 'g', 'o', 'e'}`

**Comment by rixner** [comment]
@alexwenbj what Python are you using that you get different results?  Here is what I get:

```
Python 3.6.9 (default, Nov  7 2019, 10:44:02)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> print(set('google'))
{'g', 'l', 'o', 'e'}
>>> print(set('google'))
{'g', 'l', 'o', 'e'}
>>> print(set('google'))
{'g', 'l', 'o', 'e'}
>>> print(set('google'))
{'g', 'l', 'o', 'e'}
>>>
```
And in Python2:

```
Python 2.7.17 (default, Nov  7 2019, 10:07:09)
[GCC 7.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> print set('google')
set(['e', 'o', 'g', 'l'])
>>> print set('google')
set(['e', 'o', 'g', 'l'])
>>> print set('google')
set(['e', 'o', 'g', 'l'])
>>> print set('google')
set(['e', 'o', 'g', 'l'])
>>> print set('google')
set(['e', 'o', 'g', 'l'])
>>>
```

The iteration order of sets is not explicitly defined by the specification, and I'm reasonably certain that CPython uses a repeatable ordering.  Regardless, I don't think this can be considered a Skulpt bug.  We could make it "randomize" the iteration order (I, in fact, do this for my classes so that students don't rely on a particular iteration order for sets or dictionaries), but that costs a little bit in performance and is not really part of Python.

**Comment by albertjan** [comment]
yeah I agree with @rixner we cannot rely on the order of set wether of not they are stable or not this is an implementation detail. it differs between versions of python so it is fine it differs between cpython and skulpt.

**Comment by alexwenbj** [comment]
I used PyCharm with Python 3.6.3. It is strange that if I run the code in terminal, the order is fix.
