### ISSUE TITLE
Lack of  __slots__

### ISSUE THREAD

**Issue by alexwenbj** [skulpt/skulpt#1050]
Lack of `__slots__`.

**Comment by s-cork** [comment]
this would be great!

to do this I think we'd need `getset_descriptors` implemented. 

that way when you declare `__slots__` you are really allocating `getset_descriptors` onto `klass.prototype`

```
class A_with_slots:
   __slots__ = ["foo"]
   def __init__(self):
      self.foo = 'bar'

>>> type(A_with_slots.foo)
member_descriptor

### note that instances don't have __dict__ attribute when you delcare __slots__
>>> A_with_slots().__dict__
Attribute Error 'A_with_slots' object has no attribute __dict__
```

in skulpt terms this might be something like... 
don't store my attributes in a dictionary... 

and possibly that's what skulpt should do by default. 

---

#### proposal - skulpt should not use `$d` at all...

the reason:
```
class A:
    pass

>>> A.__dict__
mappingproxy({...
              '__dict__': <attribute '__dict__' of 'A' objects>,
...}
>>> type(A.__dict__["__dict__"]
getset_descriptor
```

So in this sense the `klass.prototype.__dict__` can just be an instruction to return the attributes of an instance as a dictionary.

rather than storing them as a dictionary to begin with... 

When you provide `__slots__` you don't `klass.prototype.__dict__` the `getset_descriptor` so instances of `klass` can't get their attributes as `dictionary`

🤔

**Comment by alexwenbj** [comment]
Yes, it is an important feature for us.But it is a core function and I don't think I have enough confidence to do that.  😣

**Comment by s-cork** [comment]
I'm slowly working my way through the core. Aiming to get passed the point of just dipping my toes in the water and working out how things fit together... 

watch this space...  🙏

**Comment by s-cork** [comment]
While working on #1092 I played around with slots. 
I think it would be good to implement this at some point - for correctness - but I did find that using slots didn’t do anything for performance.

In part because the improvements to attribute and dictionary lookups were enough that a slots implementation didn’t do anything - in fact benchmarking showed it was slower. 

the problem was that a slot is a getset_descriptor which needed to do a type check with every call to __get__. 
And this ended up being slower than a dictionary lookup.
