### ISSUE TITLE
__class_getitem__ support

### ISSUE THREAD

**Issue by acbart** [skulpt/skulpt#1146]
I don't think there's been any work to handle `__class_getitem__`, which is new in Python 3.7. I wanted to raise it as an issue, since I'm thinking about writing some code that might rely on it and therefore might make a cursory implementation. Unless @s-cork already has it finished it somewhere... :)

**Comment by acbart** [comment]
Okay, so digging in a little, I've found that the CPython implementation adds an additional check AFTER the regular `mp_subscript` inside of `PyObject_GetItem` in `abstract.c`: https://github.com/python/cpython/blob/8182cc2e68a3c6ea5d5342fed3f1c76b0521fbc1/Objects/abstract.c#L181

So I guess that means the relevant place is here in the Skulpt version: https://github.com/skulpt/skulpt/blob/master/src/abstract.js#L606

The original code's algorithm is basically:
* Verify that the object is a type (`PyType_Check`)
* There's a special case for the builtin `type` function (*"Special case type[int], but disallow other types so str[int] fails"*) using `PyType_Type`; it returns a Generic Alias if so (which is a new thing)
* Tries to `_PyObject_LookupAttrId` to see if there's a `__class_getitem__` method
* If successful, it calls the found attribute as a method.

Something like the following?

```javascript
} else if (Sk.builtin.checkClass(o)) {
    if (o === Sk.builtin.type) {
        return // ? Py_GenericAlias
    }
    if (o.tp$class_getitem) {
        return o.tp$class_getitem(key, canSuspend);
    }
}
```

Then you'd add new entries to `Sk.dunderToSkulpt` and a new `slots.__class_getitem__`?  There needs to be a `Py_GenericAlias` class too, but I have to look deeper into what exactly that needs to have.

If anyone has input on this, I'd be interested.

**Comment by s-cork** [comment]
I’d avoid adding a slot function unless cpython also has a `tp_class_getitem` slot. 

I don't think they do. 
https://docs.python.org/3/c-api/typeobj.html

Instead I'd use 
```javascript
f = Sk.abstr.lookupSpecial(obj, Sk.builtin.str.$classgetitem)
if (f) {
    return Sk.miscecal.callsim(OrSuspend)Array(f, [obj, item])
```

**Comment by acbart** [comment]
Ah, thank you so much for linking to that page! I've been reading over the CPython source code, and it never even occurred to me to just go check the C-API docs. Goodness, I don't know how I get anything done sometimes.

Yes, I agree, your code seems much more correct. I believe from there, the only other component is to implement [GenericAlias](https://github.com/python/cpython/blob/8182cc2e68a3c6ea5d5342fed3f1c76b0521fbc1/Objects/genericaliasobject.c).

**Comment by s-cork** [comment]
I think creating `genericAlias` might be the challenging part here no? Or at least the time consuming part. 

I think with the buildNativeClass function it might be easier because you can then take a look at line 541 from cpython's genericAlias and can more easily map the functions from C to JavaScript. But I wouldn't wait on that to be approved. 

Im also not quite sure how `__mro_entries` fits into it all which might be another challenge... 

What's the intended use case out of curiosity? I've not come across it before. I looked at the pep and it seemed it was focused on the typing module...

**Comment by acbart** [comment]
I want my students to be able to write the following:

```python
def median(numbers: list[int]) -> float:
    pass
```

**Comment by s-cork** [comment]
All the lines being referred to are correct.
The issue is that `__class_getitem__` is an implied class method
So in `type.js` we need to convert it to a `classmethod` if it isn't already.

Here's what we do for `__new__` which is an implied staticmethod
https://github.com/skulpt/skulpt/blob/5f5d40d973de02b0d8316557e4a7d48ad8616f5b/src/type.js#L171-L178
