### ISSUE TITLE
Mapping a Python Function to a custom Javascript Function

### ISSUE THREAD

**Issue by evandarcy** [skulpt/skulpt#1202]
Hi,

I am working on a project which allows users to program a character in a HTML5 game using a code editor. There is a global JS object called `character` which has several methods such as `moveForwardByUnits( units )` that a user can use to 'program' their character. I would love to enable users to be able to program this game using python, and Skulpt seems absolutely perfect for that.

**Objective:**

Allow a user to be able to run a command like `character.moveForwardByUnits(10)` directly from the Skulpt editor and have that api map to the already defined Javascript object method.

**What I have tried**
I have been able to successfully achieve a mapping of a function like so:

```
function moveForwardByUnits(units){
  console.log("moving forward by " + units.v + " units!");
}

Sk.builtins.moveForwardByUnits = function( units ){moveForwardByUnits(units)}
```

I can then call `moveForwardByUnits(10)` inside the Skulpt editor where I get my expected result.

I don't see how I can achieve something like 
```
character = Character()
character.moveForwardByUnits(10)
```

Any help, guidance or a point in the right direction would be very much appreciated.

Thanks!

**Comment by s-cork** [comment]
You've got lots of options here I think. 

You could create a module like some of the modules in the skulpt src/lib directory.

The recent addition of webbrowser would be a good one to check out as it includes some functions and a class. 

Then you can add this module to `Sk.builtinFiles.files` as a string making sure that the path ends with `.js`

And if your users are writing in a text you could include the import statement at the very top of the code editor like `from MyModule import *`. 

Alternatively you could add all of these objects to `Sk.globals` rather than `Sk.builtins` and set the flag `retainGlobals` to be true in your `Sk.configure` options. 

It might be better to use `new Sk.builtin.func(function () {})` as it can get a little weird if you send JavaScript objects to your end user in skulpt.

**Comment by evandarcy** [comment]
This is really helpful, I ended up creating a module based off the example you suggested and it seems to be working as intended on my first test!

**Comment by Baloneo** [comment]
> This is really helpful, I ended up creating a module based off the example you suggested and it seems to be working as intended on my first test!

I have the same problem, is there any code for reference?
