### ISSUE TITLE
Sqlite3 is not yet implemented in Skulpt

### ISSUE THREAD

**Issue by adithraghavs** [skulpt/skulpt#1326]
Could you implement the sqlite3 module of python here? Being a default library, it is very important!

**Comment by alexwenbj** [comment]
See #1305

**Comment by s-cork** [comment]
Although sqlite3 is part of the stdlib - this is unlikely to get implemented anytime soon. Most things in skulpt get added when someone requires a missing feature and then makes a pull request with that feature.


It seems the question is about whether one of the contributors can implement sqlite3. Since the answer to that question is  - maybe but it probably won't happen - i'll close this issue for now.


Of course, if someone wants to have a go and open a pull request then please re-open. A suitable pull request would certainly be considered for skulpt's stdlib implementation given that it's part of cpython's stdlib.


For implementing sqlite3 it might work to wrap a maintained sqlite client side javascript implementation. This looks promising https://sql.js.org/#/. But I don't know enough about the library or the python implementation of sqlite3 to know if it would be suitable.


side note - if you are looking for database access in the browser with python you might also consider anvil.works which is tool for building web apps with python built on top of skulpt.
