### ISSUE TITLE
complex numbers not implemented

### ISSUE THREAD

**Issue by bnmnetp** [skulpt/skulpt#17]
Code you're trying to run:
print complex
print complex(2,1)

What does "real" Python output?
<type 'complex'>
(2+1j)

**Comment by waywaaard** [comment]
I am going to take this issue for some status updates:

Currently passing tests: ```ran 107559 tests, passed: 107559 failed: 0``` (we have to change the way how they are counted)

Just look in the unit test ```test_complex``` in my branch (https://github.com/waywaaard/skulpt/tree/epy). It also takes a few seconds (30?) for the all the complex unit tests to run.

ToDo:
- [ ] keyword arguments are currently not working (sth like ```complex(real=2, imag=1)```
- [ ] complex does not call ```_float__``` if argument is an object and implements this method
- [ ] can't really subclass exceptions and therefore I disabled a few tests
- [ ] weird bug for repr/str, though it is not really affecting anything
- [ ] divmod is supported though it is deprecated clsand could be removed
- [ ] look into ```test_richcompare_boundaries``` because those are failing, could be related to skulpt float impl.
- [ ]  ```nb$coerce``` is not implemented (this builtin is not implemented and are not essential (see docs))
- [ ] use constant ```NotImplemented``` in ```richCompare``` 

While implementing the complex type I improved a few builtin functions and some other areas. There might be a few bugs, but it should work for most cases (at least the unit tests are working).

See latest commit: https://github.com/waywaaard/skulpt/commit/30a74dfec2d46d5f381af904a79ed6821c20daf0

The next step would be to integrate my changes into the skulpt master. This won't be easy as I made some other changes for some better support for the ```Sk.python3``` flag.

**Comment by bnmnetp** [comment]
Why don't you go ahead and create the PR for this, then we can  help take a look at some of the items on the todo list and get this integrated.  It also makes it easier for others to grab your branch, try things out, and follow the progress.

**Comment by waywaaard** [comment]
I guess we can close this one.

**Comment by bnmnetp** [comment]
Yay!  Thanks a lot for your efforts on this.
