### ISSUE TITLE
textwrap

### ISSUE THREAD

**Issue by eah13** [skulpt/skulpt#261]
`fill()` and `wrap()` would be quite useful for getting well-line-broken text into the console.  Could be useful in printouts from an eventual `help()` function or other docstring dumps.  (#249)  

In the classroom: We've got some users who are teaching computational poetry.  textwrap would be very useful here. 

Some research is in order: if/how the module differs 2 vs 3 being the big one. And which to implement.  Any other decisions that need to be made or considerations?

[the 2 docs](https://docs.python.org/2/library/textwrap.html) 
[the 3 docs](https://docs.python.org/3/library/textwrap.html)

At first glance looks like 3 just adds a few things.

Edit: per @rixner's suggestion, a list of re and string things I found that need implementation for textwrap 2.x to work in skulpt:

`string`
- [ ] maketrans
- [x] expandtabs

`re`
- [ ] compile
- [ ] sub
- [ ] .pattern

**Comment by waywaaard** [comment]
```expandtabs``` has been implemented.

**Comment by s-cork** [comment]
I have a working version of textwrap. I edited the parts from the cpython github  `textwrap.py` ( a combination of the [2.7 version](https://github.com/python/cpython/blob/3.7/Lib/test/test_textwrap.py) and [3.7 version](https://github.com/python/cpython/blob/2.7/Lib/test/test_textwrap.py) with some edits where Skulpt hasn't implemented `translate` or `sub`. 

And where `re.compile(pattern).search` didn't want to work. 

One issue with the `textwrap` is that it requires the regex [assertion look behind](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/assertions) 

Chrome | Edge | Firefox | Internet Explorer | Opera | Safari | Android webview | Chrome for Android | Firefox for Android | Opera for Android | Safari on iOS | Samsung Internet | Node.js
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Full support - 62 | No support | No support [see issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1225665) | No support | Full support | No support | Full support | Full support 62 | No support [see issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1225665) | Full support 46 | No support | Full support 8.0 | Full support 8.10.0

The regex used in the code is: 
```
r'(?<=[\w\!\"\'\&\.\,\?])-{2,}(?=\w))'
```

I have it working in chrome with the above expression. But an alternative would make it more compatible.

Otherwise, I've got it to pass all tests except tests with umlauts (ä, ö, ü) and non-breaking spaces...
