### ISSUE TITLE
Font bug in new turtle

### ISSUE THREAD

**Issue by bnmnetp** [skulpt/skulpt#327]
@bzwheeler 

As I was cleaning up some odds and ends on interactivepython, I found this problem, which you can reproduce in the linked trinket.
https://trinket.io/python/d485b692c4

Notice that the second line of writing does not show up, or maybe its showing up somewhere else but we cannot see it.   If you change Arial to Bold then both lines show up.

Also, I have found that specifying the div to be display: inline-block works nicely.  Otherwise I ran across a number of cases where the browser messed with the width of the div and made it wider than the contained canvases.  which makes the graphics off center, or even worse if you set a background color the part of the div has the proper background color but part does not.

**Comment by bzwheeler** [comment]
@bnmnetp 

I don't quite understand why changing the font to bold works, still digging into that.  However, the original font strings actually are working but the screen is set to render only every 30'th update due to the `tracer(30,0)` call.  It just so happens that the first write falls on an update cycle while the 2'nd write does not.

Adding an explicit `wn.update()` after the final write causes the full graphic to be rendered, [see it working here](https://trinket.io/python/1090ee7e18).

**Comment by bnmnetp** [comment]
Ugh, I haven't been bit by the tracer update cycle behavior in a long time.
