### ISSUE TITLE
import functions from external modules from other files "py" without compiling in skulpt-stdlib.js

### ISSUE THREAD

**Issue by derykti** [skulpt/skulpt#328]
I just met the skulpt project and I am enthusiastic about his ability, apparently only supports external modules provided it has been compiled in skulpt-stdlib.js, correct?

It is possible to request functions from external modules from other files "py" declaring the "import" without compiling the modules in skulpt-stdlib.js?

Example:
import "modules/functions.py" 
or
from "modules.py" import functions

There is possibility of future import modules that way or something?

If it were possible it would be easier to create modular designs and make possible to create large and serious projects using skupt

**Comment by bnmnetp** [comment]
Hi,

``from module import function`` already works in Skulpt.   import modules/functions.py will not work nor will ``from modules.py import functions`` because they are not legal python statements to start with.

We do already support a way for third parties to host their own modules for you to import using ``Sk.externalLibraries``  For example you could host a module you call pygal as follows:

```javascript
Sk.externalLibraries = {
  pygal : {
    path : 'http://somehost.com/js/skulpt/pygal/__init__.js',
      dependencies : [
        '/components/highcharts/highcharts.js',
        '/components/highcharts/highcharts-more.js'
      ]
  },
  // ... other libraries
};
```

**Comment by muthukrishnan32** [comment]
Can you please explain me clearly on Import functionality ??

**Comment by dima13230** [comment]
Hi. I'm trying to use this method but when I try to import any module I add I get an error "no module"
