### ISSUE TITLE
Processing mouse x/y

### ISSUE THREAD

**Issue by eah13** [skulpt/skulpt#361]
Looks like the mouse x/y implementation is returning a non-int, preventing it from working as designed?  

https://trinket.io/library/trinkets/a10acb232a

**Comment by bnmnetp** [comment]
Strange, in either case I get:  ``AttributeError: 'Mouse' object has no attribute 'x' `` when I try to run it in my test page.   I'm thinking that @bzwheeler  has made some changes that haven't been pushed back, since I also remembered/verified that the implementation in the repo expects a ``canvas`` and not a ``div`` as its output element.

**Comment by bnmnetp** [comment]
Very interesting.  Many of my old examples are broken because in each case I get a problem with an attribute such as mouse.x  or Environment.frameRate not found.  In every case I had to update the ``__getattr__`` method to remap the key parameter back to a Javascript string.  I know this worked fine before, but I have no idea when it stopped.  Here is what I did. So, I have no idea how either version is working for you @eah13.

```javascript
        $loc.__getattr__ = new Sk.builtin.func(function (self, key) {
            key = Sk.ffi.remapToJs(key);
            if (key === "x") {
                return mod.processing.mouseX;
            }
            else if (key === "y") {
```

Tagging @dsblank for this discussion because I know he is working on adding giant chunks of functionality into the module.

Doug, I'm pretty sure I can push this bug fix without causing merge conflicts for you...

**Comment by bnmnetp** [comment]
OK, now that I've cleaned up the problems with getattr I see what the problem is in your example

```python
from processing import *

def draw():
    ellipse( mouse.x, mouse.y, 50, 50)  # doesn't work on Chrome :(
    #ellipse(int(mouse.x), int(mouse.y), 50, 50)  # this works - where's the rub? 
    
    print (mouse.x, mouse.y)

run()
```

the problem is that ``__getattr__`` is being bad and returning a "javascript int" NOT a "python int".  Whereas elllipse expects to get a "python int".

So, the processing module was written in a time when we were much less thoughtful about always returning proper python data types.  @dsblank as you wrap things this is important for you as well.

I'll fix up the return types on my branch so you can see what I'm referring to.

Brad

**Comment by dsblank** [comment]
I think this is fixed now too. Can be closed.

**Comment by Francyfx** [comment]
why mouseX and mouseY couldn`t useful
