### ISSUE TITLE
Operator Lookup is broken

### ISSUE THREAD

**Issue by waywaaard** [skulpt/skulpt#439]
I was fiddling around with making built-ins subclassable and setting up the numeric tower. I've discovered that following simple example fails.

```python
class Foo:
    def __init__(self):
        self.a = "a"
    def __sub__(self, other):
        return "hurray"

class Bar(Foo):
    def __init__(self):
        self.b = "b"

print Bar() -1
```

This should actually output: ```hurray``` but throws an type error. The ```Sk.abstr.boNameToSlotFuncLhs_``` should also call the ```tp$getattr``` routine. However, it seems that this is not that easy. I do not really understand all of the internal mechanisms of lookup and when the type object it used and when not.

If somebody can get this working then we are one step closer to subclassable built-ins.

**Comment by eah13** [comment]
Killer.  Chipping away at it.  Added a reference from #400 under built-in class extension.

**Comment by bnmnetp** [comment]
Actually I think this is a simpler bug.    ``__sub__`` should be used for the RHS and ``__rsub__`` should be used for the LHS.

**Comment by waywaaard** [comment]
No, the operator lookup does not use the MRO. I know all methods. Another example why this is broken.

```python
class Foo:
    def __init__(self):
        self.a = "a"
    def __sub__(self, other):
        return "hurray"

class Bar(Foo):
    def __init__(self):
        self.b = "b"

class Bah:
    def __init__(self):
        self.c = "aaa"
    
    def __sub__(self, other):
        return "bah"

print Foo() - Bah() # works __sub__ can be found on object itself
print Bar() - Foo()  # not working, MRO is not respected while searching for __sub__  
print Bar() - Bah() # same
```

**Comment by bnmnetp** [comment]
Duh, you are right.  Nevermind.

**Comment by bnmnetp** [comment]
Just messing around with it I came up with this strategy:

1.  Use obj.tp$getattr("__sub__") instead of bracket lookup.
2.  Because [] and tp$getattr return different objects this This required a modification to binary_op_ to detect the difference.  Maybe it would be better to return tp$getattr().im_func

Just putting this out there for discussion.

```
--- a/src/abstract.js
+++ b/src/abstract.js
@@ -43,7 +43,7 @@ Sk.abstr.boNameToSlotFuncLhs_ = function (obj, name) {
     case "Add":
         return obj.nb$add ? obj.nb$add : obj["__add__"];
     case "Sub":
-        return obj.nb$subtract ? obj.nb$subtract : obj["__sub__"];
+        return obj.nb$subtract ? obj.nb$subtract : obj.tp$getattr("__sub__");
     case "Mult":
         return obj.nb$multiply ? obj.nb$multiply : obj["__mul__"];
     case "Div":
@@ -153,7 +153,10 @@ Sk.abstr.binary_op_ = function (v, w, opname) {
     if (vop !== undefined) {
         if (vop.call) {
             ret = vop.call(v, w);
-        } else {
+        } else if (vop.im_func ) {
+            ret = Sk.misceval.callsim(vop.im_func, v, w);
+        }
+        else {
             ret = Sk.misceval.callsim(vop, v, w);
         }
         if (ret !== undefined) {
```

**Comment by bnmnetp** [comment]
I probably should have looked at using tp$getattr way back when I first looked at adding support for the dunder methods, but to be honest I don't think I understood what I was doing well enough.

**Comment by rixner** [comment]
I think that ```tp$getattr``` is absolutely the right way to go about doing this.  Does ```tp$getattr``` return something that has already been turned into a bound method on ```obj```?  Is it supposed to?

**Comment by bnmnetp** [comment]
The [] lookup returns an Sk.builtin.func object which seems kind of OK,  whereas tp$getattr returns an Sk.builtin.method which seems completely right.

**Comment by waywaaard** [comment]
I thought a few builtins return pure javascript functions, don't they?

**Comment by bnmnetp** [comment]
@rixner I guess this is similar to regular python.  when I do getattr(instance,'method') I get a bound method back.

**Comment by bnmnetp** [comment]
I we are in agreement that this is a good way to go, then I will be more thorough and create a full blown PR around this.

**Comment by Jacco** [comment]
Sumbled on this working on datetime as well have a applied a fix in abstr.js as well:

        return Sk.builtin.type.typeLookup(obj.ob$type,"__add__");
        // return obj.nb$add ? obj.nb$add : obj["__radd__"];

Fixed my problem.

**Comment by waywaaard** [comment]
I think this is one of the major problems of skulpt. The built-ins use the internal methods and python classes implement need to implement the magic method. The skulpt core is unfortunately not as close to the cpython source as I would wish. So the typeLookup for ```__add__``` is not sufficient as built-ins do implement ```nb$add``` -.-

**Comment by bnmnetp** [comment]
It seems to me that:

1.  @Jacco's suggestion is right on, and better than tp$getattr as it requires no additional changes to ``binary_op_``

2.  That the built-ins should first check to see if there is the corresponding dunder implementation and then call that preferring it to their own default implemenation.

**Comment by waywaaard** [comment]
correct, therefore we would need a mapping of those. I've started one somewhere but I think it is incomplete.

```javascript
var map = {
        "nb$add": "__add__",
        "nb$subtract": "__sub__",
        "nb$multiply": "__mul__",
        "nb$divide": "__div__",
        "nb$floor_divide": "__floordiv__",
        "nb$remainder": "__mod__",
        "nb$power": "__pow__",
        "nb$lshift": "__lshift__",
        "nb$rshift": "__rshift__",
        "nb$and": "__and__",
        "nb$xor": "__xor__",
        "nb$or": "__or__",
        "nb$negative": "__neg__",
        "nb$positive": "__pos__",
        "nb$invert": "__invert__",
        "$d": "__dict__",
        "tp$iter": "__iter__",
        "tp$hash": "__hash__",
        "tp$str": "__str__",
        "tp$mro": "__mro__",
        "tp$name": "__name__",
        "tp$richcompare": "__cmp__",
        "$r": "__repr__",
        "sq$length": "__len__",
        "sq$contains": "__contains__",
        "mp$length": "__len__",
        "ob$type": "__class__"
    };
```

**Comment by bnmnetp** [comment]
@rixner and @waywaaard 
Hmm, well using Sk.builtin.object.PyObject_LookupSpecial_(obj,"__sub__") sub does not work.  I have to use obj.ob$type as the parameter.  Otherwise I get:

```
UNCAUGHT EXCEPTION: ExternalError: TypeError: Cannot read property '__sub__' of undefined on line 18
```

The way I see it, it would be nice if this would return "__sub__" if that is defined, otherwise return the nb$sub if not defined.

The questions I have are should we need to alias ``__sub__`` and  nb$sub ?  If LookupSpecial fails to find something we need a better error message.

I'm definitely in favor of the one lookup function to rule them all approach, but we need to make it smart and robust.

**Comment by waywaaard** [comment]
The LookupSpecial_ requires to get a type passed in. We can still refactor this so that the function automatically looks for the type, but then we have a problem when we pass in a type directly.

The function does not support the automatic mapping of internal methods to dunder. That seemed to be pretty complicated. We should open somewhere a discussion thread or use this one to decide which approach would be the best.

**Comment by bnmnetp** [comment]
@waywaaard, I think this is as good a place as any to have the discussion.   I think most of the key information is part of this thread already.

Just to summarize what are think are the decisions.  (feel free to add as I may miss a few)

1.  Name and signature of LookupSpecial
2.  How to handle the mapping of dunder methods and internal methods

### A proposal for the function

* As @rixner suggested change the name to ``Sk.builtin.object.LookupSpecial``
* This method would take an object and a string representing the name of a dunder method
* If the passed object is not null, then get its type and  call  ``Sk.builtin.type.LookupSpecial``  A new function that accepts a type as a parameter.  If that does not return anything then check if the builtin method is defined for the object and return it.
* The return value should be a bound method that can be handed to  ``miseval.callsim``
This seems to be nice and clean, and allows us to call a type function when we have a type, and an object function when we call an object.

### A proposal for the mapping

Again there are two options proposed or prototyped:

1. having the ``type.LookupSpecial`` function use an explicit mapping like you referenced   here: https://github.com/google/pytypedecl/blob/master/slots.py

2.  Make each type explicitly alias the builtin and the dunder as you have done with ``dict``

It seems to me that at this stage, both approaches may suffer from incompleteness. We may miss a bultin or a dunder when making the maps, but it seems that the builtin  nb$xx, tp$xx, sq$xx are spread all over the place and we may very well miss making an alias.  

The explicit mapping approach feels nicer to me because you can see the mappings all in one place.  So as a proposal I would propose we go in this direction.  But I don't have very strong feelings about it, and @waywaaard you have already done dict.  So I am very interested in your opinion.

Comments?  Other options?

(mentioning @jacco and @albertjan to invite them in to this discussion as well)

**Comment by bnmnetp** [comment]
@waywaaard In looking again at what you did with ``dict`` I see that I initially missed an important detail.  You are doing more than simply making an alias, you are also creating a Python function for each dunder method, which is important.

So, perhaps following your lead is a better strategy.

If we go this way, then I propose we make a feature branch so we can distribute the workload of wrapping all of the nb$xx, tp$xx, sq$xx  functions, and the refactoring of using the LookupSpecial method(s) in all the right places.

**Comment by bnmnetp** [comment]
As I was working on the iteration stuff yesterday I came across an interesting case.

1.  I added a function called ``getIter`` to object.   
2.  I ran a test the created a class that inherited from object and then printed out the dir of an instance of that object.
3.  my new function getIter was on the list printed (and caused the test to fail)

There were two important learnings from this:

1.  I renamed my method ``getIter_`` which hid it from dir.
2.  A user class can inherit from ``object``  !?   What is different about object?  How come I can inherit from object but not from dict? int? list?

**Comment by LeszekSwirski** [comment]
> A user class can inherit from object !? What is different about object? How come I can inherit from object but not from dict? int? list?

Nothing (since the introduction of new-style classes in Python 2.4 or so), you should be able to inherit from all of these.

**Comment by bnmnetp** [comment]
@LeszekSwirski that was not my question.  I understand how that works in Real Python, the problem is that In Skulpt you currently cannot do this:

```python
class Myclass(dict):
   pass
```

But you can do

```python
class Myclass(object):
   pass
```

**Comment by LeszekSwirski** [comment]
Yes, and my point is that maybe we can get a hint by looking into how new-style classes differ from old-style classes in Real Python, because it is these which allowed subclassing builtin types.

**Comment by waywaaard** [comment]
@bnmnetp This one is easy to answer. In ```import.js``` is some bootstrapping code:

```javascript
Sk.doOneTimeInitialization = function () {
    // can't fill these out when making the type because tuple/dict aren't
    // defined yet.
    Sk.builtin.type.basesStr_ = new Sk.builtin.str("__bases__");
    Sk.builtin.type.mroStr_ = new Sk.builtin.str("__mro__");
    Sk.builtin.object["$d"] = new Sk.builtin.dict([]);
    Sk.builtin.object["$d"].mp$ass_subscript(Sk.builtin.type.basesStr_, new Sk.builtin.tuple([]));
    Sk.builtin.object["$d"].mp$ass_subscript(Sk.builtin.type.mroStr_, new Sk.builtin.tuple([Sk.builtin.object]));
};
```
However does this not add any methods or properties to the internal dictionary.

**Comment by bnmnetp** [comment]
I believe this can be closed now.
