### ISSUE TITLE
messy state with multiple time.sleep runs

### ISSUE THREAD

**Issue by eah13** [skulpt/skulpt#560]
When I repeatedly run this code (as in run it again when it's in the middle of executing)

```
import time

for i in range(10):
  print(i)
  time.sleep(1)
```

I get muddled results, as if some part of the stack isn't getting cleaned:

```
0
4  
1 
1
2
3
4
5
6
7
8
9
```

The `4` in this case corresponds to re-running the program around the time that i = 4.  The `4` I can understand.  But what's up with that second `1`?

I reproduced in vanilla skulpt too but here's a trinket to easily repro yourself: https://trinket.io/python/3541e47727  Press run then press run again once the loop's gone thru a few iterations.

(Aside: I wonder if this may be related to some hard-to-diagnose Turtle state bugs we've seen that also seem to preserve odd state across repeated runs and now that I think about it probably also used time.sleep.  If thats the case I'll open an issue refing this one)  

Thoughts?  Perhaps I'm misdiagnosing what's going on.  Hopefully there's a magic bullet to clear all leftover state/stack stuff at the beginning of the new run and this is a small one.

**Comment by LeszekSwirski** [comment]
That's a pretty interesting bug, nice catch. My guess for the second 1 is that it's a print from the previous invocation printing the new state of i. Perhaps fixing this is as simple as waiting for the previous invocation to drain before starting a new one?

**Comment by rixner** [comment]
I think that the problem here is that there is a ```setTimeout``` timer that is active when you are trying to reset the state.  This timer is not exposed anywhere, so you can't kill it.  I don't think you can just wait for it to drain - what if the call was to sleep for 5 minutes?  To solve this, I suspect we need to expose the timer ID somewhere so that you can call ```clearTimeout``` on that timer.

This is a general problem with using ```setTimeout``` within Skulpt, as the timer is not exposed to the enclosing controller so that it can easily be killed when necessary.  I think a better solution is to add another option to ```Sk.configure``` where you can provide your own ```setTimeout``` equivalent for all the places that it is used (currently image, turtle, time, and misceval).  Then, it could default to just ```setTimeout``` for those who don't care (or maybe a function that checks if you are in a browser or not and does the appropriate thing), or you could provide a function that keeps the ID's so they can be cleared for those who want to be able to reset them all.  I'm not 100% certain, but it seems like there should only ever be one timer active at any given time, so you would just have to clear that one...
