### ISSUE TITLE
Any idea how hard it would be to support unicode characters in variables ?

### ISSUE THREAD

**Issue by bnmnetp** [skulpt/skulpt#637]
I've had this request from a Swedish teacher.

**Comment by waywaaard** [comment]
I think at least from the javascript side, we are good to go. Though, I am not sure about parsing and etc. double width characters:

This does work. Though, the unicode support is only in Python3.

Javascript seems to support unicode symbols, or at least some.
```javascript
>> var Σ = 2;
>> Σ
<< 2
```

I am not sure if we need to add changes to the lexer. See https://docs.python.org/3/reference/lexical_analysis.html#identifiers and https://www.python.org/dev/peps/pep-3131/

**Comment by bjorn3** [comment]
This seems to already be mostly supported. It doesn't work for some identifiers though. For example for `রং` (U+09B0 (Bengali Letter Ra) followed by U+0982 (Bengali Sign Anusvara)) It will first tokenize `র` as `T_NAME` and then `ং` as `T_OP`. This seems to be caused by the `Name` regex only matching the first unicode codepoint and not the second.
