### ISSUE TITLE
Error calling highcharts.js with CDNs in our own server

### ISSUE THREAD

**Issue by MatrixLeadInternship** [skulpt/skulpt#683]
I tried to use pygal in skulpt to plot some graphs. As said in another issue, skulpt.js does not support CDNs with https so I put them in our own  server. But when I tried to call highcharts.js there's an error saying: ReferenceError: Can't find variable: Highcharts. Plunker link is as shown below: [https://plnkr.co/edit/XbbOoBjrNDE0gcSPJyFF?p=preview](url). Is there a solution for that or am I using it in a wrong way?
Here's one using example code in the main page of skuplt but our CDNs that works [http://plnkr.co/edit/bInVoYBlzB14CPhWJEkS?p=preview](url)
Here's another one using http CDNs that works [http://plnkr.co/edit/AEP0u46GBIIHcD3OnPGV?p=preview](url)

Best regards

**Comment by albertjan** [comment]
Right 3 things :) 

- the highchart.js file on yout plnkr.co is the highcharts-more.js file :smile: if you put this https://cdnjs.cloudflare.com/ajax/libs/highcharts/5.0.11/highcharts.js in your file. It'll load. 
- You also should load highcharts.js before highcharts-more.js so swap lines 67 and 68
- And there's a bug in skulpt that causes the stack overflow error in your console. Line 173 of __init__.js `Sk.ffi.remapToJs(self.$d);` fails because it contains a circular reference. I'll try to look into that tonight.

**Comment by albertjan** [comment]
I think it'll work if you use https://raw.githubusercontent.com/skulpt/skulpt-dist/0.11.0/skulpt.js this version of skulpt instead of the current master.

If you want to look into submitting a patch for this have a look at this function: https://github.com/skulpt/skulpt/blob/master/src/ffi.js#L53

if you pass that a dictionary that references itself it causes a stackoverflow.

```py
a = {}
b = { 'a': a }
a['b'] = b
```

```js
Sk.ffi.remapToJs(Sk.globals.a) //-> crash
```

**Comment by MatrixLeadInternship** [comment]
After I changed the CDNs to the one you gave me, it worked!
Thanks a lot for your help 👍 

As for the stack overflow bug, I'll check that later.

**Comment by eah13** [comment]
Looks like this was solved
