### ISSUE TITLE
Enable branch protection for master

### ISSUE THREAD

**Issue by albertjan** [skulpt/skulpt#701]
It might be a good idea to enable branch protection on master so we can only ever merge onto master if there's a successful travis build for the commit.

This because I just accidentally merged an upstream branch from trinkets fork into skulpts master because I resolved a merge conflict and I didn't even realise that I did that.

**Comment by albertjan** [comment]
I'll also pay more attention to these things in the future 😰

**Comment by bnmnetp** [comment]
Seems like a good idea to me.

Two options under protect this branch seem quite natural:

1.  Require pull request reviews before merging
2. Require status checks to pass before merging

The first is just enforcing what we have all agreed to do anyway.  But would force us to use the interface instead of just commenting "LGTM."  :smile: The second would make sure that travis-ci tests were passing.  Doing both is also an option, and either would have prevented the accidental merge of this morning.

Preferences?

**Comment by rixner** [comment]
It seems like checking both is reasonable.  The only downside to requiring reviews is if it further delays pull requests because it's more work than responding LGTM. :smile:

**Comment by eah13** [comment]
Branch protection will be huge. Github's interface is biased towards upstream *contributions* from forks so it's really easy to do what Albert Jan did when you're trying to pull in upstream changes. I've almost done this myself several times. 

As for the review interface, let's give it a go and see how we like it. I admit I've never really given it a chance.

**Comment by bnmnetp** [comment]
OK, I'll turn them both on.  We can always back off later if one or the other doesn't seem to work.  I've been using the review interface with my students this summer, and it works very well.  Your going to look at the code anyway, this just lets you comment on that page, rather than commenting in the discussion.
