### ISSUE TITLE
jseval is weird

### ISSUE THREAD

**Issue by prescod** [skulpt/skulpt#757]
```
>>> x = 5
>>> x = jseval("5")
>>> x
NameError: name 'x' is not defined on line 1
```
Is jseval documented anywhere? Does it do useful things?

**Comment by albertjan** [comment]
it is weird, it just runs your code in javascript, and doesn't return anything, and thats a bug.

`jseval` should probably be called `jsexec` because it doesn't return the result of the statement it just executes it. 

it could return the result of the eval.

I use it here: https://github.com/skulpt/skulpt/blob/master/test/unit/test_input.py so I guess it can be usefull.
