### ISSUE TITLE
Merging back from trinket

### ISSUE THREAD

**Issue by bnmnetp** [skulpt/skulpt#798]
@albertjan , @eah13   --- I've been trying to track down a bug in comparing types,  It seems something really weird was happening.  Running `print(type('a') == type(1))` gave the expected result of False under normal skulpt testing conditions and in a simple web page. But when running with Suspensions it would return `True`  in fact any sort of type comparison returned `True` . `type([1,2,3]) == str` was `True`.  After hours of trying to find and fix the problem I tested it under trinket and it worked fine.  So 
 I merged the Trinket Fork back to a branch on my runestone fork.  -- This fixed the problem for me as well.  There were only a couple of minor merge conflicts which were easily resolvable.

I have a feeling I picked up a lot of other nice bug fixes as well.

So.... Is there any way we can get back together and combine forces again?

**Comment by albertjan** [comment]
@bnmnetp Every time I make changes to the trinkets branch of skulpt upstreaming those changes is part of the discussion. 😄 There are like you said a few bug fixes and there is a bigger change around async calls to `Sk.read` and and making the `onBeforeImport` async. It has been on my agenda to do a PR to upstream the bigger stuff. 

The type check bug has to do with a python2 python3 difference 😄 we caught that a little while ago. And there may be a few more bugs we've fixed, I will have to check.

Mostly the changes on the trinket branch are the `super`, `relative imports`, and `function descriptor` pr's that are due to get merged in. 

I would like to take the time to correctly split the changes out into a few PR's so we can discuss them separately.

**Comment by bnmnetp** [comment]
Thanks @albertjan ,

I was looking through the code and noticed that the python2 / python3 split is much more developed on the trinket branch.  How do you do the equivalent of `Sk.python3 = True` on the trinket side?  I noticed that all my print's reverted to python2 behavior.

I would be very happy to put in some time to get things synced back up, especially on the core stuff.

The type checking stuff is making me crazy as we are going to be teaching and using JSON files

**Comment by albertjan** [comment]
So on trinkets branch every python3 specific change has it’s own flag. There are I believe two presets in env.js. So you would set ‘Sk.__future__ = Sk.python3’.

**Comment by bnmnetp** [comment]
Thanks @albertjan, I just changed the object passed to configure to contain ``__future__ : Sk.python3,``  and all my python3 goodness came back.
