### ISSUE TITLE
Minimum JavaScript version?

### ISSUE THREAD

**Issue by LeszekSwirski** [skulpt/skulpt#841]
I've been wondering, what are people's browser support matrices like these days? In particular, skulpt currently avoids (as far as I know) ES6 features, which I believe are by now supported by basically every actively used browser. We could get code health and performance boosts from allowing more modern JS features, like classes (which offer optimisations relating to object shape) or rest parameters (like accessing `arguments` but less terrible).

**Comment by j-f1** [comment]
#719

**Comment by albertjan** [comment]
@LeszekSwirski I've been working on a branch to get es6 classes and modern imports to work. And I ran into a few circular dependencies. :trollface: 

![graph](https://user-images.githubusercontent.com/301791/55405475-10db5680-5552-11e9-95fe-47391b2ba850.png)

And because you can't determine load order for web pack or node (or at least I haven't been able to find how) well it's just a bigger job then I initially thought. 

I'm also unsure if we're willing to drop ie11 support, which hardly has any of these niceties.

**Comment by LeszekSwirski** [comment]
Yeah, I wouldn't worry about modules for now, that's a whole can of worms. IE11 is indeed the most interesting blocker, hence the question.

**Comment by albertjan** [comment]
Some more modern js compiler should be able to compile to a set of required browsers, so people that don't have to support IE11 can have the faster modern javascript stuff. I'm going to close this as this will definitely be revisited at some point. 😄
