### ISSUE TITLE
About turtle ontimer() function

### ISSUE THREAD

**Issue by alexwenbj** [skulpt/skulpt#907]
In python,the `ontimer()` function can invoke multi times for multi tasks,but in Skulpt,the `ontimer()` can only run one method at one time,cause every time you invoke the `ontimer()`,it will clear the previous timer,maybe it should remove the clear timeout snippet:
```
proto.$ontimer = function(method, interval) {
            // if (this._timer) {
            //     window.clearTimeout(this._timer);
            //     this._timer = undefined;
            // }

            if (method && typeof interval === "number") {
                this._timer = window.setTimeout(method, Math.max(0, interval|0));
            }
        };
```

**Comment by Oranjoose** [comment]
Why was this closed? In the official Python turtle module, multiple ontimer events can be tracked simultaneously. Skulpt cannot track multiple timers because the timer is being cleared. Can we instead have an array of timer objects created by the setTimeout function, so that multiple timers can be tracked simultaneously?

**Comment by alexwenbj** [comment]
@Oranjoose Just comment the clear timer code as I showed in this issue can resolve this defect.
