### ISSUE TITLE
Parsing is slow because of regexes being repeatedly re-compiled in Chrome Devtools

### ISSUE THREAD

**Issue by acbart** [skulpt/skulpt#927]
#926 left me very curious about what was causing the slowdown. I did a lot of digging and manual profiling, and I think I've determined the main cause. A big chunk of time is spent calling `RegExp` inside the tokenizer, which is a very costly operation. I'm guessing that something in DevTools prevents it from caching the created regexes.

I'm not clear that this affects anyone not using DevTools in Chrome, but I know I'll be modifying this in my local fork. My plan is to simply extract out the literal values in `isidentifier`, and turn the Python3 dependent ones into something that gets setup during `Parser.setup`. Is there any interest in making that a pull request?

Offending lines: 

* https://github.com/skulpt/skulpt/blob/master/src/tokenize.js#L107
* https://github.com/skulpt/skulpt/blob/master/src/tokenize.js#L365
* https://github.com/skulpt/skulpt/blob/master/src/tokenize.js#L392
* https://github.com/skulpt/skulpt/blob/master/src/tokenize.js#L425

**Comment by albertjan** [comment]
So this only affects the speed if you have dev tools open? I agree we should cache that massive identifier regex in `isidentifier` and we can also do the unicode check once instead of everytime.

On the other ones I'm hesitant because regexes in javascript are stateful 🤦‍♂ so you'd need to reset the regex every time you run into it again. if we could make a function that has the same syntax but somehow caches the regexes, I'd be happy with that. 

As you probably know by now the tokeniser is a pig to debug and understand, I was hoping to wrap it up and put it in a box and never touch it again to be honest 😆

**Comment by albertjan** [comment]
You're right? https://jsbin.com/nonesagehi/edit?js,console
