### ISSUE TITLE
type() function can't return the correct package name

### ISSUE THREAD

**Issue by alexwenbj** [skulpt/skulpt#936]
For example:
```
from turtle import *
pen = Turtle()
print(type(pen))
```
it print out `<class '__main__.Turtle'>`,but it should be <class 'turtle.Turtle'>

**Comment by acbart** [comment]
Okay, so I think I figured this one out while I was solving a separate issue. It has to do with the way that JavaScript modules get loaded compared to compiled modules. Basically, I believe that JS modules need to declare their `__name__` explicitly. As in:

```javascript
var $builtinmodule = function (name) {
    var mod = {__name__: Sk.builtin.str("NAME OF MODULE GOES HERE")};
    // module code...
    return mod;
};
```

So in this case, someone needs to just add in the appropriate variable to `src/lib/turtle.js`. Of course, since Turtle is super complicated, the actual change is about 22 lines down I think:

```javascript
        var _module              = {__name__: Sk.builtin.str("turtle")},
```

But I haven't tried that in `turtle` - just in my custom `ast` module. The hilarious thing that led me to encounter this bug was that Skulpt was eager to assign SOME module name to imported classes, and was using the name of the first named module that imported the unnamed module. In this case, a seemingly totally irrelevant module was being brought into the mix, and I thought I was going nuts :)

**Comment by alexwenbj** [comment]
@acbart Yeah,It works!Thank you!
